###
GET https://lichess.org/api/account/email
Content-Type: application/json
Authorization: Bearer lip_D8TJFPK1r8qd9m7sXmxI

###
POST https://lichess.org/api/token
Content-Type: application/json

{
    "code": "liu_njzoZQ9q6QwFcE09a1kaxA1rqOx9WxMm",
		"grant_type": "authorization_code",
		"code_verifier": "LtU3UnPQM02QGYseIBOKThd8XlIIadPRClZ08Sz9tzo",
		"redirect_uri": "/",
		"client_id": "mktour.org",
}