###
GET https://lichess.org/api/account
Content-Type: application/json
Authorization: Bearer {BEARER_TOKEN}

###
GET https://lichess.org/api/player/autocomplete?term=yatskov
Authorization: Bearer {BEARER_TOKEN}
